name = "portfolio-web-9xkcig"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[vars]
NODE_ENV = "production"
VITE_BASE_URL = "https://www.ageha734.jp"
VITE_GOOGLE_ANALYTICS_ENABLED = true
VITE_GOOGLE_TAG_MANAGER_ENABLED = true
VITE_XSTATE_INSPECTOR_ENABLED = false
VITE_SENTRY_ENVIRONMENT = "production"
VITE_SENTRY_TRACES_SAMPLE_RATE = "0.1"
VITE_SENTRY_REPLAY_SAMPLE_RATE = "0.1"
VITE_SENTRY_REPLAY_ON_ERROR_SAMPLE_RATE = "1.0"
