name = "portfolio-api-tntk2h"
compatibility_date = "2025-11-17"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
NODE_ENV = "development"

[durable_objects]
bindings = [
    { name = "CHAT_ROOMS", class_name = "ChatRoomDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoomDO"]
